"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AppLocale = "en" | "ta" | "hi" | "te" | "kn" | "ml";
const STORAGE_KEY = "p4u_locale";
const authMessages: Record<AppLocale, Record<string, string>> = {
  en: { "auth.create":"Create Account", "auth.join":"Join Planext4u and start shopping", "auth.phoneWindow":"Phone verification window", "auth.expired":"This verification link has expired.", "auth.verifyAgain":"Verify phone again", "auth.customOccupation":"Or type your own", "auth.accept":"Tap to read and accept", "auth.signIn":"Sign in", "auth.forgot":"Forgot password?", "auth.new":"New to Planext4u?", "auth.secureOtp":"Secure phone verification", "auth.enterOtp":"Enter your verification code", "auth.resend":"Resend code" },
  ta: { "auth.create":"கணக்கை உருவாக்கு", "auth.join":"Planext4u-வில் இணைந்து வாங்கத் தொடங்குங்கள்", "auth.phoneWindow":"தொலைபேசி சரிபார்ப்பு", "auth.expired":"இந்த சரிபார்ப்பு இணைப்பு காலாவதியானது.", "auth.verifyAgain":"தொலைபேசியை மீண்டும் சரிபார்க்கவும்", "auth.customOccupation":"அல்லது நீங்களே உள்ளிடுங்கள்", "auth.accept":"படித்து ஏற்க தட்டவும்", "auth.signIn":"உள்நுழைக", "auth.forgot":"கடவுச்சொல் மறந்துவிட்டதா?", "auth.new":"Planext4u-க்கு புதியவரா?", "auth.secureOtp":"பாதுகாப்பான தொலைபேசி சரிபார்ப்பு", "auth.enterOtp":"சரிபார்ப்புக் குறியீட்டை உள்ளிடுங்கள்", "auth.resend":"குறியீட்டை மீண்டும் அனுப்பு" },
  hi: { "auth.create":"खाता बनाएँ", "auth.join":"Planext4u से जुड़ें और खरीदारी शुरू करें", "auth.phoneWindow":"फ़ोन सत्यापन", "auth.expired":"यह सत्यापन लिंक समाप्त हो गया है।", "auth.verifyAgain":"फ़ोन दोबारा सत्यापित करें", "auth.customOccupation":"या स्वयं लिखें", "auth.accept":"पढ़ने और स्वीकार करने के लिए टैप करें", "auth.signIn":"साइन इन", "auth.forgot":"पासवर्ड भूल गए?", "auth.new":"Planext4u पर नए हैं?", "auth.secureOtp":"सुरक्षित फ़ोन सत्यापन", "auth.enterOtp":"सत्यापन कोड दर्ज करें", "auth.resend":"कोड फिर भेजें" },
  te: { "auth.create":"ఖాతా సృష్టించండి", "auth.join":"Planext4uలో చేరి షాపింగ్ ప్రారంభించండి", "auth.phoneWindow":"ఫోన్ ధృవీకరణ", "auth.expired":"ఈ ధృవీకరణ లింక్ గడువు ముగిసింది.", "auth.verifyAgain":"ఫోన్‌ను మళ్లీ ధృవీకరించండి", "auth.customOccupation":"లేదా మీరే నమోదు చేయండి", "auth.accept":"చదివి అంగీకరించడానికి నొక్కండి", "auth.signIn":"సైన్ ఇన్", "auth.forgot":"పాస్‌వర్డ్ మర్చిపోయారా?", "auth.new":"Planext4uకి కొత్తవారా?", "auth.secureOtp":"సురక్షిత ఫోన్ ధృవీకరణ", "auth.enterOtp":"ధృవీకరణ కోడ్ నమోదు చేయండి", "auth.resend":"కోడ్ మళ్లీ పంపండి" },
  kn: { "auth.create":"ಖಾತೆ ರಚಿಸಿ", "auth.join":"Planext4u ಸೇರಿ ಖರೀದಿ ಆರಂಭಿಸಿ", "auth.phoneWindow":"ಫೋನ್ ಪರಿಶೀಲನೆ", "auth.expired":"ಈ ಪರಿಶೀಲನಾ ಲಿಂಕ್ ಅವಧಿ ಮುಗಿದಿದೆ.", "auth.verifyAgain":"ಫೋನ್ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ", "auth.customOccupation":"ಅಥವಾ ನೀವೇ ನಮೂದಿಸಿ", "auth.accept":"ಓದಿ ಒಪ್ಪಲು ಟ್ಯಾಪ್ ಮಾಡಿ", "auth.signIn":"ಸೈನ್ ಇನ್", "auth.forgot":"ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?", "auth.new":"Planext4uಗೆ ಹೊಸಬರೇ?", "auth.secureOtp":"ಸುರಕ್ಷಿತ ಫೋನ್ ಪರಿಶೀಲನೆ", "auth.enterOtp":"ಪರಿಶೀಲನಾ ಕೋಡ್ ನಮೂದಿಸಿ", "auth.resend":"ಕೋಡ್ ಮತ್ತೆ ಕಳುಹಿಸಿ" },
  ml: { "auth.create":"അക്കൗണ്ട് സൃഷ്ടിക്കുക", "auth.join":"Planext4u-ൽ ചേർന്ന് ഷോപ്പിംഗ് ആരംഭിക്കുക", "auth.phoneWindow":"ഫോൺ സ്ഥിരീകരണം", "auth.expired":"ഈ സ്ഥിരീകരണ ലിങ്കിന്റെ കാലാവധി കഴിഞ്ഞു.", "auth.verifyAgain":"ഫോൺ വീണ്ടും സ്ഥിരീകരിക്കുക", "auth.customOccupation":"അല്ലെങ്കിൽ സ്വന്തമായി നൽകുക", "auth.accept":"വായിച്ച് അംഗീകരിക്കാൻ ടാപ്പ് ചെയ്യുക", "auth.signIn":"സൈൻ ഇൻ", "auth.forgot":"പാസ്‌വേഡ് മറന്നോ?", "auth.new":"Planext4u-ൽ പുതിയ ആളാണോ?", "auth.secureOtp":"സുരക്ഷിത ഫോൺ സ്ഥിരീകരണം", "auth.enterOtp":"സ്ഥിരീകരണ കോഡ് നൽകുക", "auth.resend":"കോഡ് വീണ്ടും അയയ്ക്കുക" },
};
const commerceMessages: Record<AppLocale, Record<string, string>> = {
  en: { "orders.title":"My Orders", "orders.none":"No orders yet.", "order.details":"Order Details", "order.deliveryReturns":"Delivery & returns", "order.track":"Track with courier", "order.awaitingTracking":"Tracking updates will appear here once the seller ships your order.", "order.confirmDelivery":"Confirm delivery", "order.requestReturn":"Request return", "order.bill":"Bill Details", "order.itemTotal":"Item Total (MRP)", "order.deliveryFee":"Delivery Fee", "order.free":"FREE", "order.grandTotal":"Grand Total", "order.info":"Order Info", "order.id":"Order ID", "order.placed":"Placed on", "order.payment":"Payment", "order.deliverTo":"Deliver to", "order.paymentRef":"Payment reference", "cart.deliverTo":"Deliver To", "cart.coupon":"Coupon", "cart.points":"Redeem Points", "cart.total":"Total Amount", "cart.empty":"Your cart is empty", "cart.start":"Add some products to get started!", "cart.payment":"Payment Method", "cart.changeAddress":"Change Delivery Address", "cart.savedAddresses":"Saved Addresses" },
  ta: { "orders.title":"எனது ஆர்டர்கள்", "orders.none":"ஆர்டர்கள் இன்னும் இல்லை.", "order.details":"ஆர்டர் விவரங்கள்", "order.deliveryReturns":"விநியோகம் & திரும்பப்பெறுதல்", "order.track":"கூரியர் மூலம் கண்காணிக்கவும்", "order.awaitingTracking":"விற்பனையாளர் ஆர்டரை அனுப்பியதும் கண்காணிப்பு தகவல்கள் இங்கே தோன்றும்.", "order.confirmDelivery":"விநியோகத்தை உறுதிசெய்", "order.requestReturn":"திரும்பப்பெற கோருங்கள்", "order.bill":"பில் விவரங்கள்", "order.itemTotal":"பொருட்களின் மொத்தம் (MRP)", "order.deliveryFee":"விநியோகக் கட்டணம்", "order.free":"இலவசம்", "order.grandTotal":"மொத்தத் தொகை", "order.info":"ஆர்டர் தகவல்", "order.id":"ஆர்டர் எண்", "order.placed":"ஆர்டர் செய்த நாள்", "order.payment":"பணம் செலுத்தல்", "order.deliverTo":"விநியோக முகவரி", "order.paymentRef":"பணம் செலுத்திய குறிப்பு", "cart.deliverTo":"விநியோக முகவரி", "cart.coupon":"கூப்பன்", "cart.points":"புள்ளிகளைப் பயன்படுத்தவும்", "cart.total":"மொத்தத் தொகை", "cart.empty":"உங்கள் வண்டி காலியாக உள்ளது", "cart.start":"தொடங்க சில பொருட்களைச் சேர்க்கவும்!", "cart.payment":"பணம் செலுத்தும் முறை", "cart.changeAddress":"விநியோக முகவரியை மாற்று", "cart.savedAddresses":"சேமித்த முகவரிகள்" },
  hi: { "orders.title":"मेरे ऑर्डर", "orders.none":"अभी कोई ऑर्डर नहीं।", "order.details":"ऑर्डर विवरण", "order.deliveryReturns":"डिलीवरी और वापसी", "order.track":"कूरियर से ट्रैक करें", "order.awaitingTracking":"विक्रेता द्वारा ऑर्डर भेजने के बाद ट्रैकिंग अपडेट यहाँ दिखेंगे।", "order.confirmDelivery":"डिलीवरी की पुष्टि करें", "order.requestReturn":"वापसी का अनुरोध", "order.bill":"बिल विवरण", "order.itemTotal":"वस्तु कुल (MRP)", "order.deliveryFee":"डिलीवरी शुल्क", "order.free":"मुफ़्त", "order.grandTotal":"कुल राशि", "order.info":"ऑर्डर जानकारी", "order.id":"ऑर्डर आईडी", "order.placed":"ऑर्डर की तारीख", "order.payment":"भुगतान", "order.deliverTo":"डिलीवरी पता", "order.paymentRef":"भुगतान संदर्भ", "cart.deliverTo":"डिलीवरी पता", "cart.coupon":"कूपन", "cart.points":"पॉइंट्स उपयोग करें", "cart.total":"कुल राशि", "cart.empty":"आपका कार्ट खाली है", "cart.start":"शुरू करने के लिए कुछ उत्पाद जोड़ें!", "cart.payment":"भुगतान विधि", "cart.changeAddress":"डिलीवरी पता बदलें", "cart.savedAddresses":"सहेजे गए पते" },
  te: { "orders.title":"నా ఆర్డర్లు", "orders.none":"ఇంకా ఆర్డర్లు లేవు.", "order.details":"ఆర్డర్ వివరాలు", "order.deliveryReturns":"డెలివరీ & రిటర్న్స్", "order.track":"కొరియర్‌తో ట్రాక్ చేయండి", "order.confirmDelivery":"డెలివరీని నిర్ధారించండి", "order.requestReturn":"రిటర్న్ కోరండి", "order.bill":"బిల్ వివరాలు", "order.itemTotal":"వస్తువుల మొత్తం (MRP)", "order.deliveryFee":"డెలివరీ రుసుము", "order.free":"ఉచితం", "order.grandTotal":"మొత్తం", "order.info":"ఆర్డర్ సమాచారం", "order.id":"ఆర్డర్ ఐడి", "order.placed":"ఆర్డర్ తేదీ", "order.payment":"చెల్లింపు", "order.deliverTo":"డెలివరీ చిరునామా", "order.paymentRef":"చెల్లింపు సూచన", "cart.empty":"మీ కార్ట్ ఖాళీగా ఉంది", "cart.payment":"చెల్లింపు విధానం" },
  kn: { "orders.title":"ನನ್ನ ಆರ್ಡರ್‌ಗಳು", "orders.none":"ಇನ್ನೂ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ.", "order.details":"ಆರ್ಡರ್ ವಿವರಗಳು", "order.deliveryReturns":"ವಿತರಣೆ & ಹಿಂತಿರುಗಿಸುವಿಕೆ", "order.track":"ಕೊರಿಯರ್ ಮೂಲಕ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", "order.confirmDelivery":"ವಿತರಣೆ ದೃಢೀಕರಿಸಿ", "order.requestReturn":"ಹಿಂತಿರುಗಿಸಲು ವಿನಂತಿಸಿ", "order.bill":"ಬಿಲ್ ವಿವರಗಳು", "order.itemTotal":"ವಸ್ತುಗಳ ಒಟ್ಟು (MRP)", "order.deliveryFee":"ವಿತರಣಾ ಶುಲ್ಕ", "order.free":"ಉಚಿತ", "order.grandTotal":"ಒಟ್ಟು ಮೊತ್ತ", "order.info":"ಆರ್ಡರ್ ಮಾಹಿತಿ", "order.id":"ಆರ್ಡರ್ ಐಡಿ", "order.placed":"ಆರ್ಡರ್ ದಿನಾಂಕ", "order.payment":"ಪಾವತಿ", "order.deliverTo":"ವಿತರಣಾ ವಿಳಾಸ", "order.paymentRef":"ಪಾವತಿ ಉಲ್ಲೇಖ", "cart.empty":"ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ", "cart.payment":"ಪಾವತಿ ವಿಧಾನ" },
  ml: { "orders.title":"എന്റെ ഓർഡറുകൾ", "orders.none":"ഇതുവരെ ഓർഡറുകളില്ല.", "order.details":"ഓർഡർ വിവരങ്ങൾ", "order.deliveryReturns":"ഡെലിവറി & റിട്ടേൺ", "order.track":"കൊറിയർ ഉപയോഗിച്ച് ട്രാക്ക് ചെയ്യുക", "order.confirmDelivery":"ഡെലിവറി സ്ഥിരീകരിക്കുക", "order.requestReturn":"തിരികെ നൽകാൻ അഭ്യർത്ഥിക്കുക", "order.bill":"ബിൽ വിവരങ്ങൾ", "order.itemTotal":"ഇനങ്ങളുടെ ആകെ (MRP)", "order.deliveryFee":"ഡെലിവറി ഫീസ്", "order.free":"സൗജന്യം", "order.grandTotal":"ആകെ തുക", "order.info":"ഓർഡർ വിവരം", "order.id":"ഓർഡർ ഐഡി", "order.placed":"ഓർഡർ തീയതി", "order.payment":"പണമടയ്ക്കൽ", "order.deliverTo":"ഡെലിവറി വിലാസം", "order.paymentRef":"പേയ്മെന്റ് റഫറൻസ്", "cart.empty":"നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്", "cart.payment":"പണമടയ്ക്കൽ രീതി" },
};
const featureMessages: Record<AppLocale, Record<string, string>> = {
  en: { "service.filters":"Filters", "service.available":"Available", "service.noImage":"No image", "service.none":"No services found. Try another category or filter.", "service.book":"Book your service", "service.chooseTime":"Choose a convenient time", "service.selectDate":"Select date", "service.selectTime":"Select time", "service.full":"Full", "service.allBooked":"All listed times are already booked. Try another date.", "service.about":"About this service", "service.reviews":"Customer reviews", "service.writeReview":"Write a review", "service.noReviews":"No reviews yet", "service.firstReview":"Be the first to share your experience.", "property.find":"Find Home", "property.near":"Homes near you", "property.post":"Post Property", "property.search":"Search", "property.all":"All", "property.buy":"Buy", "property.rent":"Rent", "property.my":"My properties" },
  ta: { "service.filters":"வடிப்பான்கள்", "service.available":"கிடைக்கிறது", "service.noImage":"படம் இல்லை", "service.none":"சேவைகள் கிடைக்கவில்லை. வேறு வகை அல்லது வடிப்பானை முயற்சிக்கவும்.", "service.book":"உங்கள் சேவையை முன்பதிவு செய்யுங்கள்", "service.chooseTime":"வசதியான நேரத்தைத் தேர்ந்தெடுக்கவும்", "service.selectDate":"தேதியைத் தேர்ந்தெடுக்கவும்", "service.selectTime":"நேரத்தைத் தேர்ந்தெடுக்கவும்", "service.full":"நிரம்பியது", "service.allBooked":"பட்டியலிட்ட எல்லா நேரங்களும் முன்பதிவு செய்யப்பட்டுள்ளன. வேறு தேதியை முயற்சிக்கவும்.", "service.about":"இந்த சேவை பற்றி", "service.reviews":"வாடிக்கையாளர் மதிப்புரைகள்", "service.writeReview":"மதிப்புரை எழுதுங்கள்", "service.noReviews":"மதிப்புரைகள் இன்னும் இல்லை", "service.firstReview":"உங்கள் அனுபவத்தை முதலில் பகிருங்கள்.", "property.find":"வீடு தேடல்", "property.near":"உங்களுக்கு அருகிலுள்ள வீடுகள்", "property.post":"சொத்தைப் பதிவிடுங்கள்", "property.search":"தேடுங்கள்", "property.all":"அனைத்தும்", "property.buy":"வாங்க", "property.rent":"வாடகை", "property.my":"எனது சொத்துகள்" },
  hi: { "service.filters":"फ़िल्टर", "service.available":"उपलब्ध", "service.noImage":"चित्र नहीं", "service.none":"कोई सेवा नहीं मिली। दूसरी श्रेणी या फ़िल्टर आज़माएँ।", "service.book":"अपनी सेवा बुक करें", "service.chooseTime":"सुविधाजनक समय चुनें", "service.selectDate":"तारीख चुनें", "service.selectTime":"समय चुनें", "service.full":"भरा हुआ", "service.allBooked":"सभी समय बुक हैं। दूसरी तारीख आज़माएँ।", "service.about":"इस सेवा के बारे में", "service.reviews":"ग्राहक समीक्षाएँ", "service.writeReview":"समीक्षा लिखें", "service.noReviews":"अभी कोई समीक्षा नहीं", "service.firstReview":"अपना अनुभव साझा करने वाले पहले व्यक्ति बनें।", "property.find":"घर खोजें", "property.near":"आपके पास के घर", "property.post":"संपत्ति पोस्ट करें", "property.search":"खोजें", "property.all":"सभी", "property.buy":"खरीदें", "property.rent":"किराया", "property.my":"मेरी संपत्तियाँ" },
  te: { "service.filters":"ఫిల్టర్లు", "service.available":"అందుబాటులో ఉంది", "service.noImage":"చిత్రం లేదు", "service.none":"సేవలు కనబడలేదు. మరొక వర్గం లేదా ఫిల్టర్ ప్రయత్నించండి.", "service.book":"మీ సేవను బుక్ చేయండి", "service.chooseTime":"అనుకూలమైన సమయాన్ని ఎంచుకోండి", "service.selectDate":"తేదీ ఎంచుకోండి", "service.selectTime":"సమయం ఎంచుకోండి", "service.full":"నిండింది", "service.about":"ఈ సేవ గురించి", "service.reviews":"కస్టమర్ సమీక్షలు", "service.writeReview":"సమీక్ష రాయండి", "service.noReviews":"ఇంకా సమీక్షలు లేవు", "property.find":"ఇల్లు వెతకండి", "property.near":"మీ సమీపంలోని ఇళ్లు", "property.post":"ఆస్తిని పోస్ట్ చేయండి", "property.search":"శోధించండి", "property.all":"అన్నీ", "property.buy":"కొనండి", "property.rent":"అద్దె", "property.my":"నా ఆస్తులు" },
  kn: { "service.filters":"ಫಿಲ್ಟರ್‌ಗಳು", "service.available":"ಲಭ್ಯವಿದೆ", "service.noImage":"ಚಿತ್ರವಿಲ್ಲ", "service.none":"ಸೇವೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಬೇರೆ ವರ್ಗ ಅಥವಾ ಫಿಲ್ಟರ್ ಪ್ರಯತ್ನಿಸಿ.", "service.book":"ನಿಮ್ಮ ಸೇವೆಯನ್ನು ಬುಕ್ ಮಾಡಿ", "service.chooseTime":"ಅನುಕೂಲಕರ ಸಮಯ ಆಯ್ಕೆಮಾಡಿ", "service.selectDate":"ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ", "service.selectTime":"ಸಮಯ ಆಯ್ಕೆಮಾಡಿ", "service.full":"ತುಂಬಿದೆ", "service.about":"ಈ ಸೇವೆಯ ಬಗ್ಗೆ", "service.reviews":"ಗ್ರಾಹಕ ವಿಮರ್ಶೆಗಳು", "service.writeReview":"ವಿಮರ್ಶೆ ಬರೆಯಿರಿ", "service.noReviews":"ಇನ್ನೂ ವಿಮರ್ಶೆಗಳಿಲ್ಲ", "property.find":"ಮನೆ ಹುಡುಕಿ", "property.near":"ನಿಮ್ಮ ಹತ್ತಿರದ ಮನೆಗಳು", "property.post":"ಆಸ್ತಿ ಪೋಸ್ಟ್ ಮಾಡಿ", "property.search":"ಹುಡುಕಿ", "property.all":"ಎಲ್ಲಾ", "property.buy":"ಖರೀದಿ", "property.rent":"ಬಾಡಿಗೆ", "property.my":"ನನ್ನ ಆಸ್ತಿಗಳು" },
  ml: { "service.filters":"ഫിൽട്ടറുകൾ", "service.available":"ലഭ്യമാണ്", "service.noImage":"ചിത്രമില്ല", "service.none":"സേവനങ്ങളൊന്നും കണ്ടെത്തിയില്ല. മറ്റൊരു വിഭാഗമോ ഫിൽട്ടറോ പരീക്ഷിക്കുക.", "service.book":"സേവനം ബുക്ക് ചെയ്യുക", "service.chooseTime":"സൗകര്യപ്രദമായ സമയം തിരഞ്ഞെടുക്കുക", "service.selectDate":"തീയതി തിരഞ്ഞെടുക്കുക", "service.selectTime":"സമയം തിരഞ്ഞെടുക്കുക", "service.full":"നിറഞ്ഞു", "service.about":"ഈ സേവനത്തെക്കുറിച്ച്", "service.reviews":"ഉപഭോക്തൃ അവലോകനങ്ങൾ", "service.writeReview":"അവലോകനം എഴുതുക", "service.noReviews":"ഇതുവരെ അവലോകനങ്ങളില്ല", "property.find":"വീട് കണ്ടെത്തുക", "property.near":"നിങ്ങളുടെ സമീപമുള്ള വീടുകൾ", "property.post":"സ്വത്ത് പോസ്റ്റ് ചെയ്യുക", "property.search":"തിരയുക", "property.all":"എല്ലാം", "property.buy":"വാങ്ങുക", "property.rent":"വാടക", "property.my":"എന്റെ സ്വത്തുകൾ" },
};

const propertyExtraMessages: Record<AppLocale, Record<string, string>> = {
  en: { "property.tagline":"Find, list and manage verified properties.", "property.browse":"Browse", "property.messages":"Messages", "property.tools":"Tools", "property.estimate":"Estimate", "property.searchPlaceholder":"Search city, locality, property", "property.allTypes":"All property types", "property.saveSearch":"Save search", "property.loading":"Loading properties...", "property.none":"No properties found", "property.tryFilter":"Try another location or filter." },
  ta: { "property.tagline":"சரிபார்க்கப்பட்ட சொத்துகளைத் தேடவும், பட்டியலிடவும், நிர்வகிக்கவும்.", "property.browse":"உலாவுக", "property.messages":"செய்திகள்", "property.tools":"கருவிகள்", "property.estimate":"மதிப்பீடு", "property.searchPlaceholder":"நகரம், பகுதி அல்லது சொத்தைத் தேடுங்கள்", "property.allTypes":"அனைத்து சொத்து வகைகளும்", "property.saveSearch":"தேடலைச் சேமிக்கவும்", "property.loading":"சொத்துகள் ஏற்றப்படுகின்றன...", "property.none":"சொத்துகள் கிடைக்கவில்லை", "property.tryFilter":"வேறு இடம் அல்லது வடிப்பானை முயற்சிக்கவும்." },
  hi: { "property.tagline":"सत्यापित संपत्तियाँ खोजें, सूचीबद्ध करें और प्रबंधित करें।", "property.browse":"ब्राउज़", "property.messages":"संदेश", "property.tools":"उपकरण", "property.estimate":"मूल्यांकन", "property.searchPlaceholder":"शहर, इलाका या संपत्ति खोजें", "property.allTypes":"सभी संपत्ति प्रकार", "property.saveSearch":"खोज सहेजें", "property.loading":"संपत्तियाँ लोड हो रही हैं...", "property.none":"कोई संपत्ति नहीं मिली", "property.tryFilter":"दूसरा स्थान या फ़िल्टर आज़माएँ।" },
  te: { "property.tagline":"ధృవీకరించిన ఆస్తులను వెతకండి, జాబితా చేయండి, నిర్వహించండి.", "property.browse":"బ్రౌజ్", "property.messages":"సందేశాలు", "property.tools":"సాధనాలు", "property.estimate":"అంచనా", "property.searchPlaceholder":"నగరం, ప్రాంతం లేదా ఆస్తిని వెతకండి", "property.allTypes":"అన్ని ఆస్తి రకాలు", "property.saveSearch":"శోధనను సేవ్ చేయండి", "property.loading":"ఆస్తులు లోడ్ అవుతున్నాయి...", "property.none":"ఆస్తులు కనబడలేదు", "property.tryFilter":"మరొక ప్రాంతం లేదా ఫిల్టర్ ప్రయత్నించండి." },
  kn: { "property.tagline":"ಪರಿಶೀಲಿಸಿದ ಆಸ್ತಿಗಳನ್ನು ಹುಡುಕಿ, ಪಟ್ಟಿ ಮಾಡಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ.", "property.browse":"ಬ್ರೌಸ್", "property.messages":"ಸಂದೇಶಗಳು", "property.tools":"ಉಪಕರಣಗಳು", "property.estimate":"ಅಂದಾಜು", "property.searchPlaceholder":"ನಗರ, ಪ್ರದೇಶ ಅಥವಾ ಆಸ್ತಿ ಹುಡುಕಿ", "property.allTypes":"ಎಲ್ಲಾ ಆಸ್ತಿ ಪ್ರಕಾರಗಳು", "property.saveSearch":"ಹುಡುಕಾಟ ಉಳಿಸಿ", "property.loading":"ಆಸ್ತಿಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...", "property.none":"ಆಸ್ತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ", "property.tryFilter":"ಬೇರೆ ಸ್ಥಳ ಅಥವಾ ಫಿಲ್ಟರ್ ಪ್ರಯತ್ನಿಸಿ." },
  ml: { "property.tagline":"സ്ഥിരീകരിച്ച വസ്തുക്കൾ കണ്ടെത്തുക, പട്ടികപ്പെടുത്തുക, നിയന്ത്രിക്കുക.", "property.browse":"ബ്രൗസ്", "property.messages":"സന്ദേശങ്ങൾ", "property.tools":"ഉപകരണങ്ങൾ", "property.estimate":"വിലയിരുത്തൽ", "property.searchPlaceholder":"നഗരം, പ്രദേശം അല്ലെങ്കിൽ വസ്തു തിരയുക", "property.allTypes":"എല്ലാ വസ്തു തരങ്ങളും", "property.saveSearch":"തിരയൽ സൂക്ഷിക്കുക", "property.loading":"വസ്തുക്കൾ ലോഡ് ചെയ്യുന്നു...", "property.none":"വസ്തുക്കളൊന്നും കണ്ടെത്തിയില്ല", "property.tryFilter":"മറ്റൊരു സ്ഥലമോ ഫിൽട്ടറോ പരീക്ഷിക്കുക." },
};
const messages: Record<AppLocale, Record<string, string>> = {
  en: { "nav.home":"Home", "nav.shop":"Shop", "nav.socio":"Socio", "nav.services":"Services", "nav.findHome":"Find Home", "nav.classified":"Classified Ads", "nav.seller":"Become a Seller", "language.title":"Language", "language.saved":"Language preference saved", "report.title":"Report", "report.private":"Reports are private and reviewed by our moderation team.", "report.reason":"Reason", "report.details":"Additional details (optional)", "common.cancel":"Cancel", "report.submit":"Submit report", "report.success":"Thank you. Your report was submitted for review." },
  ta: { "nav.home":"முகப்பு", "nav.shop":"கடை", "nav.socio":"சமூகம்", "nav.services":"சேவைகள்", "nav.findHome":"வீடு தேடல்", "nav.classified":"வகைப்படுத்தப்பட்ட விளம்பரங்கள்", "nav.seller":"விற்பனையாளராகுங்கள்", "language.title":"மொழி", "language.saved":"மொழி விருப்பம் சேமிக்கப்பட்டது", "report.title":"புகாரளி", "report.private":"புகார்கள் தனிப்பட்டவை; அவை எங்கள் மதிப்பாய்வுக் குழுவால் பரிசீலிக்கப்படும்.", "report.reason":"காரணம்", "report.details":"கூடுதல் விவரங்கள் (விருப்பம்)", "common.cancel":"ரத்து செய்", "report.submit":"புகாரை சமர்ப்பி", "report.success":"நன்றி. உங்கள் புகார் மதிப்பாய்வுக்காக சமர்ப்பிக்கப்பட்டது." },
  hi: { "nav.home":"होम", "nav.shop":"दुकान", "nav.socio":"समुदाय", "nav.services":"सेवाएँ", "nav.findHome":"घर खोजें", "nav.classified":"वर्गीकृत विज्ञापन", "nav.seller":"विक्रेता बनें", "language.title":"भाषा", "language.saved":"भाषा की पसंद सहेजी गई", "report.title":"रिपोर्ट करें", "report.private":"रिपोर्ट निजी होती हैं और हमारी मॉडरेशन टीम उनकी समीक्षा करती है।", "report.reason":"कारण", "report.details":"अतिरिक्त विवरण (वैकल्पिक)", "common.cancel":"रद्द करें", "report.submit":"रिपोर्ट भेजें", "report.success":"धन्यवाद। आपकी रिपोर्ट समीक्षा के लिए भेज दी गई है।" },
  te: { "nav.home":"హోమ్", "nav.shop":"షాప్", "nav.socio":"సమాజం", "nav.services":"సేవలు", "nav.findHome":"ఇల్లు వెతకండి", "nav.classified":"వర్గీకృత ప్రకటనలు", "nav.seller":"విక్రేతగా మారండి", "language.title":"భాష", "language.saved":"భాష ఎంపిక సేవ్ చేయబడింది", "report.title":"నివేదించండి", "report.private":"నివేదికలు గోప్యంగా ఉంటాయి మరియు మా మోడరేషన్ బృందం సమీక్షిస్తుంది.", "report.reason":"కారణం", "report.details":"అదనపు వివరాలు (ఐచ్ఛికం)", "common.cancel":"రద్దు", "report.submit":"నివేదికను పంపండి", "report.success":"ధన్యవాదాలు. మీ నివేదిక సమీక్ష కోసం పంపబడింది." },
  kn: { "nav.home":"ಮುಖಪುಟ", "nav.shop":"ಅಂಗಡಿ", "nav.socio":"ಸಮುದಾಯ", "nav.services":"ಸೇವೆಗಳು", "nav.findHome":"ಮನೆ ಹುಡುಕಿ", "nav.classified":"ವರ್ಗೀಕೃತ ಜಾಹೀರಾತುಗಳು", "nav.seller":"ಮಾರಾಟಗಾರರಾಗಿ", "language.title":"ಭಾಷೆ", "language.saved":"ಭಾಷೆಯ ಆಯ್ಕೆ ಉಳಿಸಲಾಗಿದೆ", "report.title":"ವರದಿ ಮಾಡಿ", "report.private":"ವರದಿಗಳು ಖಾಸಗಿಯಾಗಿರುತ್ತವೆ ಮತ್ತು ನಮ್ಮ ನಿರ್ವಹಣಾ ತಂಡ ಪರಿಶೀಲಿಸುತ್ತದೆ.", "report.reason":"ಕಾರಣ", "report.details":"ಹೆಚ್ಚುವರಿ ವಿವರಗಳು (ಐಚ್ಛಿಕ)", "common.cancel":"ರದ್ದು", "report.submit":"ವರದಿ ಸಲ್ಲಿಸಿ", "report.success":"ಧನ್ಯವಾದಗಳು. ನಿಮ್ಮ ವರದಿಯನ್ನು ಪರಿಶೀಲನೆಗೆ ಸಲ್ಲಿಸಲಾಗಿದೆ." },
  ml: { "nav.home":"ഹോം", "nav.shop":"കട", "nav.socio":"സമൂഹം", "nav.services":"സേവനങ്ങൾ", "nav.findHome":"വീട് കണ്ടെത്തുക", "nav.classified":"ക്ലാസിഫൈഡ് പരസ്യങ്ങൾ", "nav.seller":"വിൽപ്പനക്കാരനാകുക", "language.title":"ഭാഷ", "language.saved":"ഭാഷാ മുൻഗണന സംരക്ഷിച്ചു", "report.title":"റിപ്പോർട്ട് ചെയ്യുക", "report.private":"റിപ്പോർട്ടുകൾ സ്വകാര്യമാണ്; ഞങ്ങളുടെ മോഡറേഷൻ സംഘം അവ പരിശോധിക്കും.", "report.reason":"കാരണം", "report.details":"കൂടുതൽ വിവരങ്ങൾ (ഐച്ഛികം)", "common.cancel":"റദ്ദാക്കുക", "report.submit":"റിപ്പോർട്ട് സമർപ്പിക്കുക", "report.success":"നന്ദി. നിങ്ങളുടെ റിപ്പോർട്ട് പരിശോധനയ്ക്കായി സമർപ്പിച്ചു." },
};
type LocaleValue = { locale: AppLocale; setLocale: (value: AppLocale) => void; t: (key: string, fallback?: string) => string; formatCurrency: (value: number) => string; formatDate: (value: string | number | Date) => string };
const LocaleContext = createContext<LocaleValue | null>(null);

export function LocaleProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<AppLocale>("en");
  useEffect(() => { const saved = localStorage.getItem(STORAGE_KEY) as AppLocale | null; if (saved && saved in messages) setLocaleState(saved); }, []);
  const setLocale = (value: AppLocale) => { setLocaleState(value); localStorage.setItem(STORAGE_KEY, value); document.documentElement.lang = value; };
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  const value = useMemo<LocaleValue>(() => ({
    locale,
    setLocale,
    t: (key: string, fallback = key) => {
      const translated = messages[locale][key] || authMessages[locale][key] || commerceMessages[locale][key] || featureMessages[locale][key] || propertyExtraMessages[locale][key] || messages.en[key] || authMessages.en[key] || commerceMessages.en[key] || featureMessages.en[key] || propertyExtraMessages.en[key];
      if (!translated && process.env.NODE_ENV !== "production") console.warn(`[i18n] Missing translation key: ${key}`);
      return translated || fallback;
    },
    formatCurrency: (value: number) => new Intl.NumberFormat(`${locale}-IN`, { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(value),
    formatDate: (value: string | number | Date) => new Intl.DateTimeFormat(`${locale}-IN`, { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)),
  }), [locale]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}

export function useLocale() { const value = useContext(LocaleContext); if (!value) throw new Error("useLocale must be used inside LocaleProvider"); return value; }
