"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { propertiesApi, type PropertyRow } from "@/lib/api/properties";
import { classifiedApi } from "@/lib/api/classified";
import { useLocale } from "@/providers/LocaleContext";

type Tab = "browse" | "mine" | "messages" | "tools";
const fieldClass = "h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-teal-500";
const money = (value: unknown) => `₹${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
const messageOf = (error: unknown) => error instanceof Error ? error.message : "Request failed";
export default function PropertyWorkspace() {
  const { t } = useLocale();
  const [tab, setTab] = useState<Tab>("browse");
  const [items, setItems] = useState<PropertyRow[]>([]);
  const [mine, setMine] = useState<PropertyRow[]>([]);
  const [messages, setMessages] = useState<Record<string, unknown>[]>([]);
  const [saved, setSaved] = useState<Record<string, unknown>[]>([]);
  const [rent, setRent] = useState<Record<string, unknown>[]>([]);
  const [q, setQ] = useState("");
  const [type, setType] = useState("");
  const [propertyType, setPropertyType] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [showPost, setShowPost] = useState(false);
  const [postSuccess, setPostSuccess] = useState("");

  const loadBrowse = useCallback(async () => {
    setLoading(true); setError("");
    try { const result = await propertiesApi.list({ q: q || undefined, type: type || undefined, propertyType: propertyType || undefined, limit: 100 }); setItems(result.items || []); }
    catch (requestError) { setItems([]); setError(messageOf(requestError)); }
    finally { setLoading(false); }
  }, [q, type, propertyType]);

  const loadAccount = useCallback(async () => {
    const [myRows, messageRows, savedRows, rentRows] = await Promise.all([propertiesApi.mine(), propertiesApi.messages(), propertiesApi.savedSearches(), propertiesApi.rentTrackers()]);
    setMine(myRows || []); setMessages(messageRows || []); setSaved(savedRows || []); setRent(rentRows || []);
  }, []);

  useEffect(() => { const timer=window.setTimeout(() => void loadBrowse(), 250); return () => window.clearTimeout(timer); }, [loadBrowse]);
  useEffect(() => { void loadAccount().catch(() => undefined); }, [loadAccount]);

  async function saveCurrentSearch() {
    try { await propertiesApi.saveSearch({ name: q || `${type || "All"} properties`, query: { q, type, propertyType }, notify: true }); setSaved(await propertiesApi.savedSearches()); }
    catch (requestError) { setError(messageOf(requestError)); }
  }

  return <div className="min-h-screen  px-3 py-5 sm:px-6"><div className="mx-auto flex w-full max-w-7xl bg-white  flex-col rounded-[28px] border border-slate-200/80 bg-white/95 p-4 shadow-[0_18px_60px_rgba(32,33,36,0.08)] sm:p-6">
    <div className="flex shrink-0 flex-wrap items-end justify-between gap-4"><div><p className="font-semibold text-teal-700">{t("property.find")}</p><h1 className="text-3xl font-black text-neutral-900">{t("property.near")}</h1><p className="text-slate-500">{t("property.tagline")}</p></div><button onClick={() => setShowPost(true)} className="rounded-xl bg-teal-600 px-5 py-3 font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg">{t("property.post")}</button></div>
    <nav className="z-20 mt-4 flex shrink-0 gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white/95 p-2 shadow-sm backdrop-blur">{([['browse','property.browse'],['mine','property.my'],['messages','property.messages'],['tools','property.tools']] as const).map(([id,key]) => <button key={id} onClick={() => setTab(id)} className={`shrink-0 rounded-xl px-4 py-2.5 text-sm font-bold transition ${tab === id ? "bg-teal-600 text-white shadow-sm" : "text-slate-600 hover:bg-slate-50"}`}>{t(key)}</button>)}</nav>
    {tab === "browse" && <div className="mt-3 flex shrink-0 gap-2 overflow-x-auto">{[["","property.all"],["sale","property.buy"],["rent","property.rent"]].map(([value,key]) => <button key={key} type="button" onClick={() => setType(value)} className={`rounded-full border px-4 py-2 text-sm font-bold ${type === value ? "bg-teal-50 text-teal-800" : "bg-white text-slate-700"}`}>{t(key)}</button>)}<button type="button" onClick={() => setTab("tools")} className="rounded-full border bg-white px-4 py-2 text-sm font-bold text-slate-700">EMI</button><button type="button" onClick={() => setTab("tools")} className="rounded-full border bg-white px-4 py-2 text-sm font-bold text-slate-700">{t("property.estimate")}</button></div>}
    {error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
    {postSuccess && <p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-800">{postSuccess}</p>}
    <div className="min-h-0 flex-1">
    {tab === "browse" && <Browse items={items} loading={loading} q={q} setQ={setQ} type={type} setType={setType} propertyType={propertyType} setPropertyType={setPropertyType} search={loadBrowse} saveSearch={saveCurrentSearch} />}
    {tab === "mine" && <MyListings rows={mine} refresh={loadAccount} setError={setError} />}
    {tab === "messages" && <Messages rows={messages} />}
    {tab === "tools" && <Tools saved={saved} rent={rent} refresh={loadAccount} setError={setError} />}
    </div>
    {showPost && <PropertyForm onClose={() => setShowPost(false)} onSaved={async () => {
      setShowPost(false);
      setTab("mine");
      setPostSuccess("Property submitted for review. Sale / rent / lease type was saved with your listing.");
      window.setTimeout(() => setPostSuccess(""), 8000);
      await loadAccount();
    }} setError={setError} />}
  </div></div>;
}

function Browse({ items, loading, q, setQ, type, setType, propertyType, setPropertyType, search, saveSearch }: { items: PropertyRow[]; loading: boolean; q: string; setQ:(v:string)=>void; type:string; setType:(v:string)=>void; propertyType:string; setPropertyType:(v:string)=>void; search:()=>Promise<void>; saveSearch:()=>Promise<void> }) {
  const { t } = useLocale();
  return <section className="flex min-h-0 flex-col lg:h-full">
    <div className="mt-4 grid shrink-0 gap-2 rounded-2xl border border-blue-100 bg-white/90 p-3 shadow-[0_10px_30px_rgba(137,207,240,0.07)] md:grid-cols-[1fr_150px_180px_auto_auto]">
      <input className={fieldClass} value={q} onChange={(event)=>setQ(event.target.value)} placeholder={t("property.searchPlaceholder")}/>
      <select className={fieldClass} value={type} onChange={(event)=>setType(event.target.value)}><option value="">{t("property.all")}</option><option value="sale">{t("property.buy")}</option><option value="rent">{t("property.rent")}</option></select>
      <select className={fieldClass} value={propertyType} onChange={(event)=>setPropertyType(event.target.value)}><option value="">{t("property.allTypes")}</option><option value="apartment">Apartment / flat</option><option value="house">Independent house</option><option value="villa">Villa</option><option value="plot">Residential plot / land</option><option value="agricultural_land">Agricultural / farm land</option><option value="commercial_office">Commercial office</option><option value="commercial_shop">Shop / showroom</option><option value="warehouse">Warehouse / godown</option><option value="pg">PG / hostel</option></select>
      <button onClick={()=>void search()} className="rounded-xl bg-neutral-900 px-4 font-bold text-white">{t("property.search")}</button><button onClick={()=>void saveSearch()} className="rounded-xl border bg-white px-4 font-bold">{t("property.saveSearch")}</button>
    </div>
    <div className="min-h-0 flex-1 lg:pr-2">
      {loading?<p className="py-16 text-center text-slate-500">{t("property.loading")}</p>:<><p className="mt-4 font-bold text-neutral-900">{t("property.near")}</p><div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((row)=><PropertyCard key={row.id} row={row}/>)}</div></>}
      {!loading&&!items.length&&<div className="py-16 text-center"><p className="font-bold text-neutral-900">{t("property.none")}</p><p className="mt-1 text-sm text-slate-500">{t("property.tryFilter")}</p></div>}
    </div>
  </section>;
}

function PropertyCard({ row }: { row: PropertyRow }) {
  return <article className="overflow-hidden rounded-2xl border bg-white shadow-sm">{row.image_url?<img src={row.image_url} alt="" className="h-44 w-full object-cover"/>:<div className="flex h-44 items-center justify-center bg-teal-50 font-semibold text-teal-700">Property photo</div>}<div className="p-4"><div className="flex justify-between gap-2"><h2 className="font-bold">{row.title}</h2><span className="text-xs font-bold uppercase text-teal-700">{row.transaction_type}</span></div><p className="mt-1 text-sm text-slate-500">{[row.locality,row.city].filter(Boolean).join(', ')}</p><p className="mt-3 text-xl font-black">{money(row.price)}</p><p className="mt-2 line-clamp-2 text-sm text-slate-600">{row.description}</p><div className="mt-4 grid grid-cols-2 gap-2"><Link href={`/find-home/${encodeURIComponent(row.id)}`} className="rounded-xl border border-teal-600 py-2 text-center font-bold text-teal-700">View details</Link><button onClick={()=>{const text=window.prompt('Message to owner:','I am interested in this property');if(text)void propertiesApi.inquire(row.id,text).then(()=>window.alert('Inquiry sent')).catch((error)=>window.alert(messageOf(error)));}} className="rounded-xl bg-teal-600 py-2 font-bold text-white">Contact owner</button></div></div></article>;
}

function MyListings({ rows, refresh, setError }: { rows:PropertyRow[]; refresh:()=>Promise<void>; setError:(v:string)=>void }) {
  async function edit(row: PropertyRow) {
    const title = window.prompt('Property title', row.title);
    if (title == null) return;
    const price = window.prompt('Property price', String(row.price || ''));
    if (price == null) return;
    try {
      await propertiesApi.update(row.id, { title: title.trim(), price: Number(price) });
      await refresh();
    } catch (error) {
      setError(messageOf(error));
    }
  }
  return <section className="mt-5 space-y-3">{rows.map((row)=><article key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-5"><div className="flex min-w-0 flex-1 items-start gap-3">{row.image_url||row.cover_image||(Array.isArray(row.images)&&row.images[0])?<img src={String(row.image_url||row.cover_image||row.images?.[0]||"")} alt="" className="h-14 w-14 shrink-0 rounded-xl object-cover bg-slate-100"/>:<div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-xs text-slate-400">No photo</div>}<div className="min-w-0"><h2 className="font-bold">{row.title}</h2><p className="text-sm text-slate-500">{money(row.price)} · {String(row.transaction_type||row.listingType||"").replace(/_/g," ")||"listing"} · {row.locality || row.city || "No location"}</p></div></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold uppercase">{row.status}</span>{['pending','rejected'].includes(String(row.status||''))&&<button onClick={()=>void edit(row)} className="rounded-lg border px-3 py-2 text-sm font-bold text-teal-700">Edit</button>}<button onClick={async()=>{if(!window.confirm('Delete this property?'))return;try{await propertiesApi.remove(row.id);await refresh();}catch(error){setError(messageOf(error));}}} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-600">Delete</button></div></article>)}{!rows.length&&<p className="py-16 text-center text-slate-500">You have not posted a property.</p>}</section>;
}
function Messages({ rows }: { rows:Record<string,unknown>[] }) { return <section className="mt-5 space-y-3">{rows.map((row,index)=><article key={String(row.id||index)} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-bold">Property inquiry</h2><span className="text-xs font-bold uppercase text-teal-700">{String(row.status||'open')}</span></div><p className="mt-2 text-slate-700">{String(row.message||'')}</p><p className="mt-2 text-xs text-slate-400">{row.created_at?new Date(String(row.created_at)).toLocaleString():''}</p></article>)}{!rows.length&&<p className="py-16 text-center text-slate-500">No property conversations yet.</p>}</section>; }

function EmiCalculator() {
  const [amount, setAmount] = useState('5000000');
  const [rate, setRate] = useState('8.5');
  const [years, setYears] = useState('20');
  const principal = Number(amount || 0);
  const monthlyRate = Number(rate || 0) / 1200;
  const months = Number(years || 0) * 12;
  const factor = monthlyRate > 0 && months > 0 ? Math.pow(1 + monthlyRate, months) : 0;
  const emi = factor > 1 ? principal * monthlyRate * factor / (factor - 1) : 0;
  return <div className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">EMI calculator</h2><div className="mt-4 grid gap-3"><input className={fieldClass} type="number" min="1" value={amount} onChange={(event)=>setAmount(event.target.value)} placeholder="Loan amount"/><input className={fieldClass} type="number" min="0" step="0.1" value={rate} onChange={(event)=>setRate(event.target.value)} placeholder="Interest rate"/><input className={fieldClass} type="number" min="1" value={years} onChange={(event)=>setYears(event.target.value)} placeholder="Tenure years"/></div><div className="mt-4 rounded-xl bg-teal-50 p-4"><p className="text-sm text-teal-700">Estimated monthly EMI</p><p className="mt-1 text-xl font-black">{money(emi)}</p></div></div>;
}
function Tools({ saved, rent, refresh, setError }: { saved:Record<string,unknown>[]; rent:Record<string,unknown>[]; refresh:()=>Promise<void>; setError:(v:string)=>void }) {
  const [city,setCity]=useState(''); const [propertyType,setPropertyType]=useState('Apartment'); const [estimate,setEstimate]=useState<{low:number;average:number;high:number;sampleSize:number}|null>(null); const [propertyName,setPropertyName]=useState(''); const [monthlyRent,setMonthlyRent]=useState('');
  return <section className="mt-5 grid gap-5 lg:grid-cols-2"><EmiCalculator/><form onSubmit={async(event)=>{event.preventDefault();try{setEstimate(await propertiesApi.estimate({city,propertyType}));}catch(error){setError(messageOf(error));}}} className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Property value estimator</h2><div className="mt-4 grid gap-3"><input className={fieldClass} value={city} onChange={(event)=>setCity(event.target.value)} placeholder="City"/><select className={fieldClass} value={propertyType} onChange={(event)=>setPropertyType(event.target.value)}><option>Apartment</option><option>House</option><option>Plot</option><option>Commercial</option></select><button className="rounded-xl bg-teal-600 py-3 font-bold text-white">Estimate value</button></div>{estimate&&<div className="mt-4 rounded-xl bg-teal-50 p-4"><p className="text-sm text-teal-700">Based on {estimate.sampleSize} approved properties</p><p className="mt-2 text-xl font-black">{money(estimate.average)}</p><p className="text-sm">Range {money(estimate.low)} – {money(estimate.high)}</p></div>}</form><form onSubmit={async(event:FormEvent)=>{event.preventDefault();try{await propertiesApi.saveRent({propertyName,monthlyRent:Number(monthlyRent),paidMonths:[]});setPropertyName('');setMonthlyRent('');await refresh();}catch(error){setError(messageOf(error));}}} className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Rent tracker</h2><div className="mt-4 grid gap-3"><input className={fieldClass} value={propertyName} onChange={(event)=>setPropertyName(event.target.value)} placeholder="Property name"/><input className={fieldClass} type="number" min="1" value={monthlyRent} onChange={(event)=>setMonthlyRent(event.target.value)} placeholder="Monthly rent"/><button className="rounded-xl bg-neutral-900 py-3 font-bold text-white">Add tracker</button></div><div className="mt-4 space-y-2">{rent.map((row,index)=><div key={String(row.id||index)} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><b>{String(row.property_name||'Property')}</b><span>{money(row.monthly_rent)}/month</span></div>)}</div></form><div className="rounded-2xl border bg-white p-5 lg:col-span-2"><h2 className="text-lg font-bold">Saved searches</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{saved.map((row,index)=><div key={String(row.id||index)} className="rounded-xl bg-slate-50 p-3"><b>{String(row.name||'Property search')}</b><p className="text-xs text-slate-500">Notifications {row.notify?'enabled':'disabled'}</p></div>)}</div>{!saved.length&&<p className="mt-3 text-sm text-slate-500">No saved searches yet.</p>}</div></section>;
}

function LegacyPropertyForm({ onClose, onSaved, setError }: { onClose:()=>void; onSaved:()=>Promise<void>; setError:(v:string)=>void }) {
  const [form,setForm]=useState({title:'',price:'',city:'',locality:'',listingType:'sale',propertyType:'Apartment',description:'',bhk:'',areaSqft:'',image:''}); const update=(key:string,value:string)=>setForm((current)=>({...current,[key]:value}));
  async function submit(event:FormEvent){event.preventDefault();try{await propertiesApi.create({title:form.title,price:Number(form.price),city:form.city,locality:form.locality,transaction_type:form.listingType,property_type:form.propertyType,description:form.description,bhk:Number(form.bhk||0),area_sqft:Number(form.areaSqft||0),images:form.image?[form.image]:[]});await onSaved();}catch(error){setError(messageOf(error));}}
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-neutral-950/60 p-4" onMouseDown={onClose}><form onSubmit={submit} onMouseDown={(event)=>event.stopPropagation()} className="max-h-[calc(100dvh-2rem)] w-full max-w-2xl overflow-y-auto overscroll-contain rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">Post a property</h2><button type="button" onClick={onClose}>✕</button></div><div className="mt-5 grid gap-3 md:grid-cols-2"><input required minLength={5} className={`${fieldClass} md:col-span-2`} value={form.title} onChange={(event)=>update('title',event.target.value)} placeholder="Property title"/><input required type="number" min="1" className={fieldClass} value={form.price} onChange={(event)=>update('price',event.target.value)} placeholder="Price"/><select className={fieldClass} value={form.listingType} onChange={(event)=>update('listingType',event.target.value)}><option value="sale">For sale</option><option value="rent">For rent</option></select><input className={fieldClass} value={form.city} onChange={(event)=>update('city',event.target.value)} placeholder="City"/><input className={fieldClass} value={form.locality} onChange={(event)=>update('locality',event.target.value)} placeholder="Locality"/><select className={fieldClass} value={form.propertyType} onChange={(event)=>update('propertyType',event.target.value)}><option>Apartment</option><option>House</option><option>Plot</option><option>Commercial</option></select><input type="number" className={fieldClass} value={form.bhk} onChange={(event)=>update('bhk',event.target.value)} placeholder="BHK"/><input type="number" className={fieldClass} value={form.areaSqft} onChange={(event)=>update('areaSqft',event.target.value)} placeholder="Area (sq ft)"/><input className={fieldClass} value={form.image} onChange={(event)=>update('image',event.target.value)} placeholder="Image URL"/><textarea rows={4} className="rounded-xl border p-3 md:col-span-2" value={form.description} onChange={(event)=>update('description',event.target.value)} placeholder="Description"/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border px-5 py-3 font-bold">Cancel</button><button className="rounded-xl bg-teal-600 px-5 py-3 font-bold text-white">Submit for review</button></div></form></div>;
}

const PROPERTY_TYPES: Array<[string,string]> = [["apartment","Apartment / flat"],["house","Independent house"],["villa","Villa"],["plot","Residential plot / land"],["agricultural_land","Agricultural / farm land"],["commercial_office","Commercial office"],["commercial_shop","Shop / showroom"],["warehouse","Warehouse / godown"],["pg","PG / hostel"]];
const PROPERTY_AMENITIES: Array<[string,string]> = [["lift","Lift"],["power_backup","Power backup"],["security","24×7 security"],["water_supply","Water supply"],["gym","Gym"],["pool","Swimming pool"],["park","Park"],["clubhouse","Clubhouse"],["internet","Internet"],["air_conditioning","Air conditioning"],["gas_pipeline","Gas pipeline"],["rainwater_harvesting","Rainwater harvesting"],["pet_friendly","Pet friendly"]];

function PropertyForm({ onClose, onSaved, setError }: { onClose:()=>void; onSaved:()=>Promise<void>; setError:(v:string)=>void }) {
  const [form,setForm]=useState<Record<string,string|boolean|string[]>>({ transaction_type:"sale",property_type:"apartment",posted_by:"owner",title:"",description:"",price:"",price_negotiable:true,maintenance:"",security_deposit:"",brokerage:"",state:"",city:"",locality:"",address:"",landmark:"",pincode:"",area_sqft:"",area_unit:"sqft",carpet_area:"",bhk:"",bathrooms:"",balconies:"",floor:"",total_floors:"",property_age_years:"",plot_length:"",plot_width:"",road_width:"",boundary_wall:false,furnishing:"unfurnished",ownership:"freehold",availability:"ready",available_from:"",facing:"east",parking:"none",gated_community:false,amenities:[],contact_name:"",contact_phone:"",image_urls:"" });
  const [photos,setPhotos]=useState<File[]>([]); const [loading,setLoading]=useState(false);
  const update=(key:string,value:string|boolean|string[])=>setForm((current)=>({...current,[key]:value}));
  const isLand=["plot","agricultural_land"].includes(String(form.property_type)); const isResidential=["apartment","house","villa","pg"].includes(String(form.property_type));
  const input=(key:string,label:string,required=false,type="text",helper="")=><label className="block text-sm font-semibold text-slate-700"><span>{label}{required ? " *" : ""}</span><input required={required} type={type} value={String(form[key]??"")} onChange={(e)=>update(key,e.target.value)} className={`${fieldClass} mt-2 w-full`}/>{helper&&<span className="mt-1 block text-xs font-normal text-slate-500">{helper}</span>}</label>;
  const section=(title:string,subtitle:string,children:React.ReactNode)=><fieldset className="rounded-2xl border border-slate-200 p-4"><legend className="px-2 text-lg font-bold text-neutral-900">{title}</legend><p className="mb-4 text-xs text-slate-500">{subtitle}</p><div className="grid gap-4 md:grid-cols-2">{children}</div></fieldset>;
  async function submit(event:FormEvent){event.preventDefault();if(!photos.length&&!String(form.image_urls).split(/[\n,]/).some((v)=>/^https?:\/\//i.test(v.trim()))){setError("Add at least one property photo or image URL.");return;}setLoading(true);try{const urls=String(form.image_urls).split(/[\n,]/).map((v)=>v.trim()).filter((v)=>/^https?:\/\//i.test(v));if(photos.length)urls.push(...await classifiedApi.uploadImages(photos));await propertiesApi.create({...form,image_urls:urls,image_url:urls[0],images:urls,price:Number(form.price||0),maintenance:Number(form.maintenance||0),security_deposit:Number(form.security_deposit||0),brokerage:Number(form.brokerage||0),area_sqft:Number(form.area_sqft||0),carpet_area:Number(form.carpet_area||0),bhk:Number(form.bhk||0),bathrooms:Number(form.bathrooms||0),balconies:Number(form.balconies||0),floor:form.floor?Number(form.floor):null,total_floors:form.total_floors?Number(form.total_floors):null,property_age_years:form.property_age_years?Number(form.property_age_years):null,plot_length:form.plot_length?Number(form.plot_length):null,plot_width:form.plot_width?Number(form.plot_width):null,road_width:form.road_width?Number(form.road_width):null});await onSaved();}catch(error){setError(messageOf(error));}finally{setLoading(false);}}
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-neutral-950/60 p-4" onMouseDown={onClose}><form onSubmit={submit} onMouseDown={(e)=>e.stopPropagation()} className="max-h-[calc(100dvh-2rem)] w-full max-w-4xl space-y-4 overflow-y-auto overscroll-contain rounded-3xl bg-[#F8FBFF] p-4 shadow-2xl sm:p-7"><div className="sticky -top-4 z-20 flex items-center justify-between border-b border-slate-200 bg-white/95 px-1 py-4 backdrop-blur sm:-top-7"><div><h2 className="text-2xl font-black">Post Property</h2><p className="text-sm text-slate-500">Complete every listing detail used by the mobile app.</p></div><button type="button" onClick={onClose} className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-100 text-2xl">×</button></div>
    {section("Listing purpose","Choose how you want to offer this property.",<><div className="md:col-span-2 grid grid-cols-3 gap-2">{[["sale","Sell"],["rent","Rent"],["lease","Lease"]].map(([value,label])=><button key={value} type="button" onClick={()=>update("transaction_type",value)} className={`rounded-xl border px-3 py-3 font-bold ${form.transaction_type===value?"bg-teal-600 text-white":"bg-white"}`}>{label}</button>)}</div><label className="text-sm font-semibold">Property type<select value={String(form.property_type)} onChange={(e)=>update("property_type",e.target.value)} className={`${fieldClass} mt-2 w-full`}>{PROPERTY_TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-sm font-semibold">Listed by<select value={String(form.posted_by)} onChange={(e)=>update("posted_by",e.target.value)} className={`${fieldClass} mt-2 w-full`}><option value="owner">Owner</option><option value="agent">Agent / broker</option><option value="builder">Builder / developer</option></select></label></>)}
    {section("Basic details","Write a clear title and an accurate description.",<>{input("title","Property title",true,"text","Example: Spacious 3 BHK near metro station")}<label className="block text-sm font-semibold md:col-span-2">Property description *<textarea required rows={5} value={String(form.description)} onChange={(e)=>update("description",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3"/><span className="mt-1 block text-xs font-normal text-slate-500">Mention highlights, nearby places, restrictions and current condition.</span></label></>)}
    {section("Price details",form.transaction_type==="sale"?"Enter the expected total selling price.":"Enter monthly rent and move-in charges.",<>{input("price",form.transaction_type==="sale"?"Expected price":"Monthly rent",true,"number")}<label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><input type="checkbox" checked={Boolean(form.price_negotiable)} onChange={(e)=>update("price_negotiable",e.target.checked)}/>Price is negotiable</label>{input("maintenance","Monthly maintenance",false,"number")}{form.transaction_type!=="sale"&&input("security_deposit","Security deposit",false,"number")}{input("brokerage","Brokerage / commission",false,"number")}</>)}
    {section("Location","Provide the complete searchable address.",<>{input("state","State",true)}{input("city","City",true)}{input("locality","Locality / neighbourhood",true)}{input("address","Full address",true)}{input("landmark","Landmark")}{input("pincode","PIN code",true,"number")}</>)}
    {section("Area and dimensions","Use accurate measurements so buyers can compare listings.",<>{input("area_sqft",isLand?"Total land area":"Built-up area",true,"number")}<label className="text-sm font-semibold">Unit<select value={String(form.area_unit)} onChange={(e)=>update("area_unit",e.target.value)} className={`${fieldClass} mt-2 w-full`}><option value="sqft">SQFT</option><option value="sqm">SQM</option><option value="cent">CENT</option><option value="acre">ACRE</option></select></label>{!isLand&&input("carpet_area","Carpet area",false,"number")}{isLand&&<>{input("plot_length","Plot length",false,"number")}{input("plot_width","Plot width",false,"number")}{input("road_width","Approach road width",false,"number")}<label className="flex items-center gap-3"><input type="checkbox" checked={Boolean(form.boundary_wall)} onChange={(e)=>update("boundary_wall",e.target.checked)}/>Boundary wall available</label></>}</>)}
    {isResidential&&section("Rooms and building","Add the layout and building information.",<>{input("bhk","Bedrooms",true,"number")}{input("bathrooms","Bathrooms",true,"number")}{input("balconies","Balconies",false,"number")}{input("floor","Property floor",false,"number")}{input("total_floors","Total floors",false,"number")}{input("property_age_years","Property age in years",false,"number")}<label className="text-sm font-semibold">Furnishing<select value={String(form.furnishing)} onChange={(e)=>update("furnishing",e.target.value)} className={`${fieldClass} mt-2 w-full`}><option value="unfurnished">Unfurnished</option><option value="semi_furnished">Semi-furnished</option><option value="furnished">Fully furnished</option></select></label></>)}
    {section("Property status","Ownership, availability and access details.",<><label className="text-sm font-semibold">Ownership<select value={String(form.ownership)} onChange={(e)=>update("ownership",e.target.value)} className={`${fieldClass} mt-2 w-full`}><option value="freehold">Freehold</option><option value="leasehold">Leasehold</option><option value="cooperative">Co-operative society</option><option value="power_of_attorney">Power of attorney</option></select></label><label className="text-sm font-semibold">Availability<select value={String(form.availability)} onChange={(e)=>update("availability",e.target.value)} className={`${fieldClass} mt-2 w-full`}><option value="ready">Ready to move</option><option value="under_construction">Under construction</option><option value="occupied">Currently occupied</option></select></label>{input("available_from","Available / possession date",false,"text","Example: 15 September 2026")}<label className="text-sm font-semibold">Facing<select value={String(form.facing)} onChange={(e)=>update("facing",e.target.value)} className={`${fieldClass} mt-2 w-full`}>{["east","west","north","south","north_east","north_west","south_east","south_west"].map((v)=><option key={v} value={v}>{v.replaceAll("_"," ").toUpperCase()}</option>)}</select></label><label className="text-sm font-semibold">Parking<select value={String(form.parking)} onChange={(e)=>update("parking",e.target.value)} className={`${fieldClass} mt-2 w-full`}><option value="none">No parking</option><option value="bike">Bike parking</option><option value="car">Car parking</option><option value="both">Car and bike parking</option></select></label><label className="flex items-center gap-3"><input type="checkbox" checked={Boolean(form.gated_community)} onChange={(e)=>update("gated_community",e.target.checked)}/>Gated community</label></>)}
    {section("Amenities","Select every facility included with the property.",<div className="flex flex-wrap gap-2 md:col-span-2">{PROPERTY_AMENITIES.map(([value,label])=>{const selected=(form.amenities as string[]).includes(value);return <button key={value} type="button" onClick={()=>update("amenities",selected?(form.amenities as string[]).filter((v)=>v!==value):[...(form.amenities as string[]),value])} className={`rounded-full border px-3 py-2 text-sm ${selected?"bg-teal-50 font-bold text-teal-800":"bg-white"}`}>{label}</button>})}</div>)}
    {section("Property photos","Add up to 15 bright and recent photos.",<><label className="flex cursor-pointer items-center justify-center rounded-xl border border-dashed p-4 text-sm font-bold md:col-span-2">{photos.length?`${photos.length} photo(s) selected`:"Choose property photos"}<input type="file" multiple accept="image/*" className="hidden" onChange={(e)=>setPhotos(Array.from(e.target.files||[]).slice(0,15))}/></label><label className="text-sm font-semibold md:col-span-2">Or paste image URLs<textarea rows={3} value={String(form.image_urls)} onChange={(e)=>update("image_urls",e.target.value)} placeholder="Separate multiple URLs with commas or new lines" className="mt-2 w-full rounded-xl border p-3"/></label></>)}
    {section("Contact information","Buyers and tenants can reach the listing owner.",<>{input("contact_name","Contact name",true)}{input("contact_phone","Mobile / WhatsApp number",true,"tel")}</>)}
    <div className="sticky -bottom-4 z-20 flex justify-end gap-3 border-t border-slate-200 bg-white/95 px-1 py-4 backdrop-blur sm:-bottom-7"><button type="button" onClick={onClose} className="rounded-xl border px-5 py-3 font-bold">Cancel</button><button disabled={loading} className="rounded-xl bg-teal-600 px-5 py-3 font-bold text-white shadow-sm disabled:opacity-60">{loading?"Submitting listing...":"Submit Listing"}</button></div>
  </form></div>;
}
